HealthCare.MVC/Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace HealthCare.MVC.Models
{
    public class Hospital
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(50)]
        public string Addres { get; set; }

        [StringLength(25)]
        public string ContactPhone { get; set; }

        [Required]
        public DateTime StartingWorkTime { get; set; }

        [Required]
        public DateTime EndingWorkTime { get; set; }

        public int Rating { get; set; }

        public string Description { get; set; }

        public string ComplexImgUrl { get; set; }

        public string PhotoUrl { get; set; }

        ICollection<ApplicationUser> Doctors { get; set; } = new List<ApplicationUser>();
    }
}

HealthCare.MVC/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HealthCare.MVC.Models;
using HealthCare.MVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HealthCare.MVC.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private IRepositoryWrapper _repositoryWrapper;

        public BookingController(IRepositoryWrapper repositoryWrapper)
        {
            _repositoryWrapper = repositoryWrapper;
        }

        public IActionResult Index(DoctorSearchModel doctorSearchModel)
        {
            ApplicationUser doctor = _repositoryWrapper.ApplicationUser.FindByCondition(x => x.Id == doctorSearchModel.DoctorId).FirstOrDefault();
            return View(doctor);
        }
    }
}

HealthCare.MVC/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HealthCare.MVC.Models;
using HealthCare.MVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HealthCare.MVC.Controllers
{
    [Authorize]
    public class HospitalController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private IRepositoryWrapper _repoWrapper;
        private IHospitalSearchServices _hospitalSearchServices;
        private IDoctorSearchServices _doctorSearchServices;

        public HospitalController(UserManager<ApplicationUser> userManager, 
        IRepositoryWrapper repoWrapper,
        IHospitalSearchServices hospitalSerchService,
        IDoctorSearchServices doctorSearchServices) {
            _userManager = userManager;
            _repoWrapper = repoWrapper;
            _hospitalSearchServices = hospitalSerchService;
            _doctorSearchServices = doctorSearchServices;
        }

        public IActionResult Index(string hospitalName)
        {
            List<Hospital> hospitals = _hospitalSearchServices.SearchHospital(hospitalName);
            return View(hospitals);
        }

        public IActionResult Doctors(HospitalSearchModel hospitalSearchModel)
        {
            List<ApplicationUser> doctors = _doctorSearchServices.SearchDoctorsByHospitalId(hospitalSearchModel.HospitalId);
            return View(doctors);
        }
    }
}

HealthCare.MVC/Views/Hospital/Doctors.cshtml
@using HealthCare.MVC.Models
@model IEnumerable<ApplicationUser>
@{
    ViewData["Title"] = "Doctors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section heads{
    <link rel="stylesheet" href="@Url.Content("~/css/hospital/doctors.css")" type="text/css" />
}

<h2>Doctors</h2>

<div class="row">
    @foreach (ApplicationUser doctor in Model)
    {
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail">
                <img src="@doctor.PhotoUrl" class="doctor-modal-img">
                <div class="caption">
                    <h3>@doctor.FirstName @doctor.SecondName</h3>
                    <p>@doctor.UserName</p>
                    @Html.ActionLink("Enter", "Index", "Booking", new DoctorSearchModel { DoctorId = doctor.Id }, null)
                </div>
            </div>
        </div>
    }
</div>

HealthCare.MVC/Views/Hospital/Index.cshtml
@using HealthCare.MVC.Models
@model IEnumerable<Hospital>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section heads{
    <link rel="stylesheet" href="@Url.Content("~/css/hospital/hospitalindex.css")" type="text/css" />
}

<div class="row">
    <div class="col-lg-12">
        <form method="post">
            <div class="input-group search-panel">
                <input type="text" class="form-control" name="hospitalName">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search</button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    @foreach (Hospital hospital in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@hospital.ComplexImgUrl" class="hospital-modal-img">
                <div class="caption">
                    <h3>@hospital.Name</h3>
                    <p>@hospital.StartingWorkTime.TimeOfDay - @hospital.EndingWorkTime.TimeOfDay</p>
                    <p>@hospital.ContactPhone</p>
                    <p>@hospital.Addres</p>
                    <p>Rating: @hospital.Rating</p>
                    <p>@hospital.Description</p>
                    
                    @Html.ActionLink("Enter", "Doctors", "Hospital", new HospitalSearchModel { HospitalId = hospital.Id, Specialization = null }, null)
                </div>
            </div>
        </div>
    }
</div>